### ISSUE TITLE
反馈一个我遇到的bug（yml反序列化问题）

### ISSUE THREAD

**Issue by 164ebr** [myunco/LiteTeleport#10]
![IMG_20230804_080336](https://github.com/myunco/LiteTeleport/assets/86980013/e114a8c6-8ca7-489f-a8cb-f6945c75e8e6)
当玩家存储了一个双等号“==”的家时插件在下次启动时候会无法读取yml文件 旧的家数据会被清楚 覆盖新的数据

==应该是yml反序列化中的特殊标记吧，过滤掉他应该就行了

**Comment by myunco** [comment]
确实存在此BUG，将在下个版本中修复。
