### ISSUE TITLE
服务器已装了ess基础插件，liteteleport能否兼容安装？

### ISSUE THREAD

**Issue by Cloudkkk** [myunco/LiteTeleport#2]
觉得传送以及设置传送点花费经验/金币的机制的很不错，想应用到服务器中，替代现有的免费传送
但是服务器已经安装了ess等插件，两者是否有优先级区别呢？
或者作者有什么办法可以兼容此类情况吗？

**Comment by myunco** [comment]
同时安装两者 通常本插件的命令会覆盖ess的命令。但ess的命令通常有不止一个别名，如/home和/ehome 如果想禁止玩家使用ess的对应命令要删除玩家使用那条命令的权限才行。

**Comment by Cloudkkk** [comment]
好的，可以一试
感谢回复
