### ISSUE TITLE
跨维度传送会丢失buff

### ISSUE THREAD

**Issue by s3xysteak** [myunco/LiteTeleport#8]
1.16.5版本，使用catserver，在主世界喝下防火药水通过/back进入下界，防火buff会消失

**Comment by myunco** [comment]
back命令不涉及任何药水效果相关操作，只是调用player.teleport方法进行传送。跨维度传送丢失药水效果的问题与本插件无关，可能是服务端设置或游戏版本特性的问题，由于我手头没有1.16.5的CatServer服务端，所以未使用CatServer进行测试，但LoliServer与CatServer相差应该不大。
经我测试 LoliServer服务端在有药水效果的情况下通过任意插件(player.teleport方法)进行跨维度传送确实会丢失药水效果，具体测试结果如下：
1.16.5 单人存档 使用execute命令传送：传送后会暂时丢失药水效果，但会在30秒内逐个恢复。
1.16.5 LoliServer服务端 使用execute命令传送：传送后会暂时丢失药水效果，但会在30秒内逐个恢复。 使用插件传送：清空药水效果。
1.16.5 Spigot服务端 使用execute命令传送：不影响药水效果。 使用插件传送：不影响药水效果。
1.16.5 Paper服务端 使用execute命令传送：不影响药水效果。 使用插件传送：不影响药水效果。

综上 此问题非插件本身问题，故我无法解决。建议提交给服务端开发者反馈。
